import { Platform } from 'react-native';
const LOCAL_IP = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';
const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || \`http://\${LOCAL_IP}:3000\`;
export interface Post { id: string; userId: string; caption: string; imagePath: string; createdAt: string; updatedAt: string; editedAt?: string | null; }
export interface PaginatedResponse { posts: Post[]; nextCursor: string | null; hasMore: boolean; }
export async function fetchPosts(cursor?: string | null, limit: number = 10): Promise<PaginatedResponse> { const params = new URLSearchParams({ limit: String(limit) }); if (cursor) params.set('cursor', cursor); const r = await fetch(\`\${API_BASE_URL}/api/posts?\${params}\`); if (!r.ok) { const e = await r.json(); throw new Error(e.error || 'Failed to fetch posts'); } return r.json(); }
export function getImageUrl(imagePath: string): string { return \`\${API_BASE_URL}\${imagePath}\`; }
export async function createPostApi(imageUri: string, caption: string, userId: string = 'current-user'): Promise<Post> { const fd = new FormData(); const fn = imageUri.split('/').pop() || 'photo.jpg'; const m = /\.(\w+)$/.exec(fn); fd.append('image', { uri: imageUri, name: fn, type: m ? \`image/\${m[1]}\` : 'image/jpeg' } as any); fd.append('caption', caption); fd.append('userId', userId); const r = await fetch(\`\${API_BASE_URL}/api/posts\`, { method: 'POST', body: fd, headers: { 'Content-Type': 'multipart/form-data' } }); if (!r.ok) { const e = await r.json(); throw new Error(e.error || 'Failed to create post'); } return r.json(); }
export async function deletePost(postId: string, userId: string): Promise<{ message: string }> { const r = await fetch(\`\${API_BASE_URL}/api/posts/\${postId}\`, { method: 'DELETE', headers: { 'x-user-id': userId } }); if (!r.ok) { const e = await r.json(); throw new Error(e.error || 'Failed'); } return r.json(); }
export async function updatePost(postId: string, userId: string, updates: { caption?: string }): Promise<Post> { const r = await fetch(\`\${API_BASE_URL}/api/posts/\${postId}\`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'x-user-id': userId }, body: JSON.stringify(updates) }); if (!r.ok) { const e = await r.json(); throw new Error(e.error || 'Failed'); } return r.json(); }
