INSERT INTO tags (name, type) VALUES
  ('Italian', 'cuisine'),
  ('Japanese', 'cuisine'),
  ('Mexican', 'cuisine'),
  ('Indian', 'cuisine'),
  ('Thai', 'cuisine'),
  ('Chinese', 'cuisine'),
  ('French', 'cuisine'),
  ('American', 'cuisine'),
  ('Mediterranean', 'cuisine'),
  ('Korean', 'cuisine'),
  ('Breakfast', 'meal'),
  ('Lunch', 'meal'),
  ('Dinner', 'meal'),
  ('Snack', 'meal'),
  ('Dessert', 'meal'),
  ('Brunch', 'meal'),
  ('Vegan', 'dietary'),
  ('Vegetarian', 'dietary'),
  ('Gluten-Free', 'dietary'),
  ('Keto', 'dietary'),
  ('Paleo', 'dietary'),
  ('Dairy-Free', 'dietary'),
  ('Nut-Free', 'dietary'),
  ('Low-Carb', 'dietary')
ON CONFLICT (name) DO NOTHING;
